export const GET_SLOTS_ARRAY = 'GET_SLOTS_ARRAY'
export const CLEAR_GAME = 'CLEAR_GAME'
export const RESULTS = 'RESULTS'
export const TOGGLE_SPIN = 'TOGGLE_SPIN'
export const TOGGLE_IS_READY = 'TOGGLE_RESULTS'
export const SET_CHARACTER = 'SET_CHARACTER'
export const HUNT = 'HUNT'
